# Generated by Django 5.0.2 on 2024-02-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0002_alter_role_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
