# Generated by Django 5.0.2 on 2024-02-19 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0004_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mag.recipe'),
        ),
    ]
