# Generated by Django 5.0.2 on 2024-02-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0006_alter_patient_electronic_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='electronic_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mag.electroniccard'),
        ),
    ]
